version: '3.7'

volumes:
  n8n_data:
    driver: local

services:
  n8n:
    container_name: ${N8N_CONTAINER_NAME}
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - ${N8N_PORT}:5678
    volumes:
      - n8n_data:/home/node/.n8n
